{% set version = "1.1-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcolorbrewer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RColorBrewer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RColorBrewer/RColorBrewer_{{ version }}.tar.gz
  sha256: 4f42f5423c45688b39f492c7892d93f37b4541831c8ffb140364d2bd89031ac0

build:
  noarch: generic
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RColorBrewer')"           # [not win]
    - "\"%R%\" -e \"library('RColorBrewer')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RColorBrewer
  license: Apache-2.0
  summary: Provides color schemes for maps (and other graphics) designed by Cynthia Brewer as described at http://colorbrewer2.org
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RColorBrewer
# Version: 1.1-2
# Date: 2014-12-07
# Title: ColorBrewer Palettes
# Authors@R: c(person(given = "Erich", family = "Neuwirth", role = c("aut", "cre"), email = "erich.neuwirth@univie.ac.at"))
# Author: Erich Neuwirth [aut, cre]
# Maintainer: Erich Neuwirth <erich.neuwirth@univie.ac.at>
# Depends: R (>= 2.0.0)
# Description: Provides color schemes for maps (and other graphics) designed by Cynthia Brewer as described at http://colorbrewer2.org
# License: Apache License 2.0
# Packaged: 2014-12-06 23:59:42 UTC; neuwirth
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-12-07 08:28:55
