appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: J0mkakPpAJIq4Sx+/ezCP27XNPcycU45uD//72JT9k8XOsEkZo0M/eeuyYTV+w50y6cliZwrL1gwtRd3JggMUmLtvXXOtVWSKY96fqcWsCbgPO/HWSeGMa3v3wrSOzKakk7mJezR4w1V5/WLXRQ42GrdE2KskoLmpHKWRESt71sDqnWQR8ilp2+myLg5gUCUMWm6zl6LpGSSdmpxtxi4qnJ0x7ldWnsJF14tKPMMjXjca8L4TeEjWL+izdxjQR6rNwZOykhMecNqTKIa2mfUzG7BLVJWl5HSKGvM1y8ZWjc4w1gcT48QfUs2I839QmEtUuTJUcSmwoFkp95n/Ox8+EAvQza9tmiiuyeq/PHlxjc+KO3H/6YwF9g2ihL6coofYrP0K3rzYFBwQBZxXa9LLUver/DXUwT69uZUwHQugBxfIUjekmyRCxGoLZrtwVSoGSV1i2mY8azDSYocKsnlDmFqj0WHBop0osNPG8c4i4FZ+WQ6SiZLwVr5hOfJP8zxxUV3RGauMGwlqxvMpXoYdwaKgdgoVtG16wru5iBXySfi3xU/Z4Q0AgekZOmDUoFSlHy6I68bIERPWUkHktCXymrOrnEGE66WsV3Qut/IAoH452KCtQTUPbyPH5L2klBPNFax/AhRAdRGSIx1BLlQd4bXv/+X0ZgXaVO/AkHNVew=}
